import hashlib, json, os, subprocess, sys, tempfile, types, unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; SCHEMAS = ROOT / "schemas"; SOURCE = ROOT / "tests/fixtures/runtime-overhead-catalog-v1/source.json"; SCRIPT = ROOT / "scripts/bind_runtime_overhead_catalog.py"; LAUNCHER = ROOT / "scripts/run_runtime_overhead_binding.py"; DESCRIPTOR = "daemon-build-v1.json"; LOCK = "daemon-build-v1.lock.json"
def canonical(value): return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
def load_binding():
    source, launcher = SCRIPT.read_bytes(), LAUNCHER.read_bytes(); namespace = {"__name__": "runtime_overhead_binding", "__file__": str(SCRIPT), "_EXECUTED_SOURCE": source, "_EXECUTED_LAUNCHER_SOURCE": launcher}; exec(compile(source, str(SCRIPT), "exec"), namespace); return types.SimpleNamespace(**namespace)
def run_binding(*arguments):
    bootstrap = json.loads((SCHEMAS / "daemon-core-build-v1.json").read_bytes())["build_variants"]["generator_execution"]["bootstrap_source"]
    env = os.environ.copy(); env.update({"LANG": "C", "LC_ALL": "C"})
    return subprocess.run([sys.executable, "-I", "-S", "-B", "-c", bootstrap, LAUNCHER, "--root", ROOT, "--catalog-source", SOURCE, *map(str, arguments)], cwd=ROOT, env=env, capture_output=True, text=True)
class RuntimeOverheadBindingTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls): cls.binding = load_binding(); cls.core = json.loads((SCHEMAS / "daemon-core-build-v1.lock.json").read_bytes())["digest"]; cls.catalog = json.loads((SCHEMAS / "runtime-overhead-catalog-v1.lock.json").read_bytes())["digest"]; cls.payload = (SCHEMAS / "runtime-overhead-catalog-v1.json").read_bytes()
    def test_frame_tuple_lookup_capacity_and_drift_are_exact(self):
        frame = self.binding.build_frame(self.payload, self.core, self.catalog, "test_fixture_nonproduction", True); header, catalog, index = self.binding.parse_frame(frame); self.assertEqual((len(frame), header["core_identity"], header["catalog_identity"], header["outer_identity"], header["test_only"]), (4194560, self.core, self.catalog, self.binding.outer_identity(self.core, self.catalog), True)); self.assertEqual(canonical(catalog), self.payload)
        entry, work = self.binding.lookup(index, catalog["entries"][-1]["key"]); self.assertEqual(entry, catalog["entries"][-1]); self.assertLessEqual(work["key_comparisons"], 9); self.assertLessEqual(work["key_bytes_compared"], 288)
        entries = [{"key": {"index": value}} for value in range(256)]; [entry.update(key_sha256=hashlib.sha256(canonical(entry["key"])).hexdigest()) for entry in entries]; entries.sort(key=lambda item: item["key_sha256"]); maximum_index = self.binding.catalog_index({"entries": entries}); work = [self.binding.lookup(maximum_index, entry["key"])[1] for entry in entries]; self.assertEqual(max(item["key_comparisons"] for item in work), 9); self.assertLessEqual(max(item["key_bytes_compared"] for item in work), 288); self.assertLessEqual(max(item["entry_bytes_validated"] for item in work), 16384)
        self.assertRaises(ValueError, self.binding.CatalogIndex, {"entries": entries + [entries[-1]]}); malformed = {"key": {"index": 0}, "key_sha256": entries[0]["key_sha256"] * 2}; self.assertRaises(ValueError, self.binding.CatalogIndex, {"entries": [malformed]})
        prefix, suffix = b'{"entries":[],"padding":"', b'"}\n'; maximum = prefix + b"x" * (4194304 - len(prefix) - len(suffix)) + suffix; exact = self.binding.build_frame(maximum, self.core, self.binding.catalog_identity(maximum), "test_fixture_nonproduction", True); self.assertEqual(len(exact), 4194560); self.assertEqual(self.binding.parse_frame(exact)[1]["padding"], "x" * (4194304 - len(prefix) - len(suffix)))
        for offset in (40, 76, 108, 256):
            with self.subTest(offset=offset): changed = bytearray(frame); changed[offset] ^= 1; self.assertRaises(ValueError, self.binding.parse_frame, bytes(changed))
    def test_fixture_requires_an_explicit_nonready_test_target(self):
        with self.assertRaises(ValueError): self.binding.load_inputs(ROOT, SOURCE, False)
        inputs = self.binding.load_inputs(ROOT, SOURCE, True); self.assertEqual((inputs["catalog_type"], inputs["test_only"], inputs["service_ready"]), ("test_fixture_nonproduction", True, False)); result = run_binding("--check", SCHEMAS); self.assertNotEqual(result.returncode, 0)
    def test_current_binding_artifact_and_lock_are_exact(self):
        with tempfile.TemporaryDirectory() as directory:
            artifact = Path(directory) / "turnvector-daemon"; result = run_binding("--allow-test-fixture", "--artifact", artifact, "--check", SCHEMAS); self.assertEqual(result.returncode, 0, result.stderr); descriptor = json.loads((SCHEMAS / DESCRIPTOR).read_bytes()); lock = json.loads((SCHEMAS / LOCK).read_bytes()); self.assertEqual(subprocess.run(["/usr/bin/codesign", "--verify", "--strict", artifact], capture_output=True).returncode, 0)
            core = json.loads((SCHEMAS / "daemon-core-build-v1.json").read_bytes())["section_identities"]["executable_text"]; self.assertEqual(descriptor["executable_provenance"]["code_sections"], core["sections"]); self.assertEqual((lock["digest"], lock["descriptor_sha256"]), (descriptor["identities"]["outer_daemon_build"], hashlib.sha256((SCHEMAS / DESCRIPTOR).read_bytes()).hexdigest()))
            candidate = bytearray(artifact.read_bytes()); alternative = canonical({"catalog_type": "test_fixture_nonproduction", "entries": []}); frame = self.binding.build_frame(alternative, self.core, self.binding.catalog_identity(alternative), "test_fixture_nonproduction", True); section = descriptor["embedding"]["section"]; candidate[section["file_offset"]:section["file_offset"] + len(frame)] = frame; other = Path(directory) / "other"; other.write_bytes(candidate); subprocess.run(["/usr/bin/codesign", "--force", "--sign", "-", "--identifier", "org.turnvector.daemon", "--timestamp=none", other], check=True, capture_output=True)
            for item in descriptor["executable_provenance"]["code_sections"]: self.assertEqual(hashlib.sha256(other.read_bytes()[item["file_offset"]:item["file_offset"] + item["byte_length"]]).hexdigest(), item["sha256"])
            subprocess.run(["/usr/bin/codesign", "--force", "--sign", "-", "--identifier", "org.turnvector.foemon", "--timestamp=none", other], check=True, capture_output=True); self.assertRaises(ValueError, self.binding.signing_metadata, other.read_bytes())
            forbidden = {"artifact_sha256", "binary_sha256", "catalog_payload_bytes", "cdhash", "final_binary_sha256"}; self.assertFalse(any(key in forbidden for key in self.binding.walk_keys(descriptor))); self.assertFalse(descriptor["embedding"]["service_ready"])
if __name__ == "__main__": unittest.main()
