import hashlib, json, os, shutil, subprocess, sys, tempfile, unittest
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]; GENERATOR, LAUNCHER, SCHEMAS = ROOT / "scripts/generate_daemon_core_build.py", "scripts/run_daemon_core_build.py", ROOT / "schemas"; DESCRIPTOR, LOCK = "daemon-core-build-v1.json", "daemon-core-build-v1.lock.json"; BOOTSTRAP = json.loads((SCHEMAS / DESCRIPTOR).read_bytes())["build_variants"]["generator_execution"]["bootstrap_source"]
INPUTS = ("Cargo.toml", "Cargo.lock", "rust-toolchain.toml", "crates/turnvector-core/Cargo.toml", "crates/turnvector-core/src/lib.rs", "crates/turnvector-daemon/Cargo.toml", "crates/turnvector-daemon/src/main.rs", "schemas/generation-semantics-v1.json", "schemas/generation-semantics-v1.lock.json", "scripts/generate_generation_semantics.py", "scripts/generate_daemon_core_build.py", LAUNCHER)
def canonical(value): return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
def evidence(payload, domain="turnvector:evidence:daemon-core-build", version=1): return hashlib.sha256(domain.encode() + b"\0" + version.to_bytes(4, "big") + payload).hexdigest()
class DaemonCoreBuildTests(unittest.TestCase):
    def run_generator(self, root, *args, env=None): return subprocess.run([sys.executable, "-I", "-S", "-B", "-c", BOOTSTRAP, str(root / LAUNCHER), "--root", str(root), *args], cwd=ROOT, env=env or os.environ.copy(), check=False, capture_output=True, text=True)
    def fixture(self, directory):
        root = Path(directory) / "repo"
        for relative in INPUTS: target = root / relative; target.parent.mkdir(parents=True, exist_ok=True); shutil.copy2(ROOT / relative, target)
        return root
    def generate(self, root, output): result = self.run_generator(root, "--output", str(output)); self.assertEqual(result.returncode, 0, result.stderr); return json.loads((output / DESCRIPTOR).read_bytes())
    def rejects(self, root, output, message): result = self.run_generator(root, "--output", str(output)); self.assertNotEqual(result.returncode, 0); self.assertIn(message, result.stderr)
    def test_current_lock_sections_tools_and_input_drift(self):
        with tempfile.TemporaryDirectory() as directory:
            outputs = [Path(directory) / name for name in ("one", "two")]; values = [self.generate(ROOT, output) for output in outputs]
            for name in (DESCRIPTOR, LOCK): self.assertEqual((outputs[0] / name).read_bytes(), (outputs[1] / name).read_bytes()); self.assertEqual((outputs[0] / name).read_bytes(), (SCHEMAS / name).read_bytes())
            sections, tools = values[0]["section_identities"], values[0]["toolchain"]; execution = values[0]["build_variants"]["generator_execution"]; self.assertEqual(execution["bootstrap_source"], BOOTSTRAP); self.assertEqual(execution["bootstrap_sha256"], hashlib.sha256(BOOTSTRAP.encode()).hexdigest()); self.assertTrue(sections["executable_text"]["present"] and sections["executable_text"]["byte_length"] > 0); self.assertTrue({"__text", "__stubs", "__stub_helper"} <= {item["section"] for item in sections["executable_text"]["sections"]})
            self.assertEqual(sections["native_text"], {"artifacts": [], "byte_length": 0, "present": False, "sha256": hashlib.sha256(b"").hexdigest()}); self.assertTrue(tools["python"]["runtime_files"]["file_count"] > 0); self.assertEqual(tools["python"]["flags"], {"dont_write_bytecode": True, "isolated": True, "no_site": True}); self.assertTrue(tools["rustc"]["driver_and_target_files"]); baseline = json.loads((SCHEMAS / LOCK).read_bytes())["digest"]
            for name in ("sdk", "link_inputs", "clang_resources", "linker_libraries", "xcode", "system_build"): self.assertIn(name, tools["native_link"])
            for index, relative in enumerate(item for item in INPUTS if not item.startswith("schemas/")):
                root = self.fixture(str(Path(directory) / str(index))); path = root / relative; path.write_bytes(path.read_bytes() + (b"\n// drift\n" if relative.endswith(".rs") else b"\n# drift\n")); output = Path(directory) / f"drift-{index}"; self.assertEqual(self.run_generator(root, "--output", str(output)).returncode, 0, relative); self.assertNotEqual(json.loads((output / LOCK).read_bytes())["digest"], baseline)
        self.assertEqual(self.run_generator(ROOT, "--check", str(SCHEMAS)).returncode, 0)
    def test_payload_invariance_code_identity_and_b02_authority(self):
        with tempfile.TemporaryDirectory() as directory:
            root, base = self.fixture(directory), Path(directory) / "base"; baseline = self.generate(root, base); (root / "notes.txt").write_text("unrelated\n")
            integration = root / "crates/turnvector-core/tests/unrelated.rs"; integration.parent.mkdir(); integration.write_text("#[test]\nfn unrelated() {}\n"); self.assertEqual(self.generate(root, Path(directory) / "integration"), baseline)
            debug_root = self.fixture(str(Path(directory) / "debug")); debug = debug_root / "crates/turnvector-daemon/src/debug_only.rs"; debug.write_text("pub fn value() -> u32 { 1 }\n"); (debug_root / "crates/turnvector-daemon/src/main.rs").write_text("#[cfg(debug_assertions)] mod debug_only;\nfn main() {}\n"); first = self.generate(debug_root, Path(directory) / "debug-one"); self.assertIn("crates/turnvector-daemon/src/debug_only.rs", [item["path"] for item in first["source_closure"]["files"]]); debug.write_text("pub fn value() -> u32 { 2 }\n"); second = self.generate(debug_root, Path(directory) / "debug-two"); self.assertNotEqual(first, second); payload = root / "schemas/runtime-overhead-catalog-v1.json"
            for index in range(2): payload.write_text(f"payload {index}\n"); self.assertEqual(self.generate(root, Path(directory) / f"payload-{index}"), baseline)
            extra = root / "crates/turnvector-core/src/extra.rs"; extra.write_text("pub fn value() -> u32 { 1 }\n"); (root / "crates/turnvector-core/src/lib.rs").write_text("mod extra;\n"); expanded = self.generate(root, Path(directory) / "expanded"); self.assertIn("crates/turnvector-core/src/extra.rs", [item["path"] for item in expanded["source_closure"]["files"]])
            (root / "crates/turnvector-daemon/src/main.rs").write_text('fn main() { println!("code drift"); }\n'); changed = self.generate(root, Path(directory) / "code"); self.assertNotEqual(changed["section_identities"]["executable_text"]["sha256"], expanded["section_identities"]["executable_text"]["sha256"])
            root = self.fixture(str(Path(directory) / "b02")); path = root / "schemas/generation-semantics-v1.json"; value = json.loads(path.read_bytes()); value["sampling_rng"]["splits_per_sampled_token"] = 99; blob = canonical(value); path.write_bytes(blob); lock_path = root / "schemas/generation-semantics-v1.lock.json"; lock = json.loads(lock_path.read_bytes()); lock["digest"] = evidence(blob, lock["domain"], lock["hash_schema_version"]); lock_path.write_bytes(canonical(lock)); self.rejects(root, Path(directory) / "b02-out", "current Generation Semantics")
    def test_trace_policy_vendor_and_source_stability(self):
        with tempfile.TemporaryDirectory() as directory:
            cases = []; root = self.fixture(str(Path(directory) / "source")); (root / "hidden.txt").write_text("hidden\n"); (root / "crates/turnvector-core/src/lib.rs").write_text('const X: &str = include_str!("../../../hidden.txt");\n'); cases.append((root, "undeclared runtime input")); root = self.fixture(str(Path(directory) / "env")); (root / "crates/turnvector-daemon/src/main.rs").write_text('fn main() { println!("{}", env!("CARGO_HOME")); }\n'); cases.append((root, "undeclared environment input"))
            root = self.fixture(str(Path(directory) / "config")); (root / ".cargo").mkdir(); (root / ".cargo/config.toml").write_text('[build]\nrustflags=["-Cdebug-assertions=no"]\n'); cases.append((root, "Cargo configuration")); root = self.fixture(str(Path(directory) / "remote")); (root / "Cargo.lock").write_text((root / "Cargo.lock").read_text() + '\nsource = "registry+https://example.invalid/index"\n'); cases.append((root, "vendored path dependencies"))
            for index, (root, message) in enumerate(cases): self.rejects(root, Path(directory) / f"reject-{index}", message)
            parent = Path(directory) / "ambient"; root = self.fixture(str(parent)); (parent / ".cargo").mkdir(); (parent / ".cargo/config.toml").write_text('[build]\nrustflags=["--invalid-ambient-flag"]\n'); env = os.environ.copy(); env["TMPDIR"] = str(parent); self.assertEqual(self.run_generator(root, "--output", str(Path(directory) / "ambient-out"), env=env).returncode, 0)
            root = self.fixture(str(Path(directory) / "vendor")); vendor = root / "vendor/third-party"; (vendor / "src").mkdir(parents=True); (vendor / "Cargo.toml").write_text('[package]\nname="third-party"\nversion="1.0.0"\nedition="2024"\n'); source = vendor / "src/lib.rs"; source.write_text("pub fn value() -> u32 { 1 }\n"); manifest = root / "crates/turnvector-daemon/Cargo.toml"; manifest.write_text(manifest.read_text() + '\nthird-party = { path = "../../vendor/third-party" }\n')
            (root / "crates/turnvector-daemon/src/main.rs").write_text('fn main() { println!("{}", third_party::value()); }\n'); subprocess.run(["cargo", "generate-lockfile", "--offline"], cwd=root, check=True, capture_output=True); first = self.generate(root, Path(directory) / "vendor-one"); self.assertIn("vendor/third-party/src/lib.rs", [item["path"] for item in first["source_closure"]["files"]]); source.write_text("pub fn value() -> u32 { 2 }\n"); second = self.generate(root, Path(directory) / "vendor-two"); self.assertNotEqual(first["section_identities"]["executable_text"]["sha256"], second["section_identities"]["executable_text"]["sha256"])
            (vendor / "unused.txt").write_text("not reachable\n"); self.assertEqual(self.generate(root, Path(directory) / "vendor-unused"), second); (vendor / "Cargo.toml").write_text((vendor / "Cargo.toml").read_text() + "\n[lib]\nproc-macro = true\n")
            self.rejects(root, Path(directory) / "proc-macro", "proc-macro"); root = self.fixture(str(Path(directory) / "build-script")); manifest = root / "crates/turnvector-daemon/Cargo.toml"; manifest.write_text(manifest.read_text().replace("[package]\n", '[package]\nbuild = "build.rs"\n')); (manifest.parent / "build.rs").write_text("fn main() {}\n"); self.rejects(root, Path(directory) / "build-script-out", "build scripts"); root = self.fixture(str(Path(directory) / "build-dependency")); manifest = root / "crates/turnvector-daemon/Cargo.toml"; manifest.write_text(manifest.read_text() + '\n[build-dependencies]\nturnvector-core = { path = "../turnvector-core" }\n'); self.rejects(root, Path(directory) / "build-dependency-out", "build dependencies")
            root, wrapper = self.fixture(str(Path(directory) / "race")), Path(directory) / "bin/cargo"; wrapper.parent.mkdir(); marker = Path(directory) / "marker"; real = shutil.which("cargo"); wrapper.write_text(f'#!/bin/sh\nif [ "$1" = "--version" ] && [ ! -e "{marker}" ]; then echo "// raced" >> "{root / "crates/turnvector-daemon/src/main.rs"}"; touch "{marker}"; fi\nexec "{real}" "$@"\n'); wrapper.chmod(0o755); env = os.environ.copy(); env["PATH"] = f'{wrapper.parent}:{env["PATH"]}'
            result = self.run_generator(root, "--output", str(Path(directory) / "race-out"), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("changed", result.stderr)
            root, wrapper = self.fixture(str(Path(directory) / "snapshot-race")), Path(directory) / "snapshot-bin/cargo"; wrapper.parent.mkdir(); marker = Path(directory) / "snapshot-marker"; wrapper.write_text(f'#!/bin/sh\n"{real}" "$@" || exit $?\ncase " $* " in *" build "*" --release "*) if [ ! -e "{marker}" ]; then while [ "$1" != "--manifest-path" ]; do shift; done; echo "// raced" >> "$(dirname "$2")/crates/turnvector-daemon/src/main.rs"; touch "{marker}"; fi;; esac\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'
            result = self.run_generator(root, "--output", str(Path(directory) / "snapshot-race-out"), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("snapshot changed", result.stderr)
            root, wrapper, output = self.fixture(str(Path(directory) / "link-race")), Path(directory) / "link-bin/cargo", Path(directory) / "link-race-out"; wrapper.parent.mkdir(); marker = Path(directory) / "link-marker"; sdk = Path(subprocess.run(["/usr/bin/xcrun", "--sdk", "macosx", "--show-sdk-path"], check=True, capture_output=True, text=True).stdout.strip()) / "SDKSettings.json"; wrapper.write_text(f'#!/bin/sh\n"{real}" "$@" || exit $?\ncase " $* " in *" build "*" --release "*) if [ ! -e "{marker}" ]; then echo "{sdk}" >&2; touch "{marker}"; fi;; esac\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; result = self.run_generator(root, "--output", str(output), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("linker input", result.stderr)
            root, wrapper, output = self.fixture(str(Path(directory) / "frozen-sdk")), Path(directory) / "frozen-sdk-bin/cargo", Path(directory) / "frozen-sdk-out"; wrapper.parent.mkdir(); marker = Path(directory) / "frozen-sdk-marker"; sdk_root = sdk.parent; wrapper.write_text(f'#!/bin/sh\ncase " $* " in *" build "*" --release "*) if [ -e "{marker}" ]; then [ "$SDKROOT" != "{sdk_root}" ] || exit 91; else touch "{marker}"; fi;; esac\nexec "{real}" "$@"\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; result = self.run_generator(root, "--output", str(output), env=env); self.assertEqual(result.returncode, 0, result.stderr)
            root, wrapper, output = self.fixture(str(Path(directory) / "tool-race")), Path(directory) / "tool-bin/cargo", Path(directory) / "tool-race-out"; wrapper.parent.mkdir(); marker = Path(directory) / "tool-marker"; wrapper.write_text(f'#!/bin/sh\n"{real}" "$@" || exit $?\ncase " $* " in *" build "*" --release "*) if [ ! -e "{marker}" ]; then echo "# drift" >> "$0"; touch "{marker}"; fi;; esac\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; result = self.run_generator(root, "--output", str(output), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("toolchain changed after discovery", result.stderr)
            for label, seek, message in (("type", 4, "architecture"), ("subtype", 8, "CPU subtype")):
                root, wrapper, output = self.fixture(str(Path(directory) / label)), Path(directory) / f"{label}-bin/cargo", Path(directory) / f"{label}-out"; wrapper.parent.mkdir(); marker = Path(directory) / f"{label}-marker"; wrapper.write_text(f'#!/bin/sh\n"{real}" "$@" || exit $?\ncase " $* " in *" build "*" --release "*) if [ -e "{marker}" ]; then printf "\\002\\000\\000\\000" | dd of="$CARGO_TARGET_DIR/release/turnvector-daemon" bs=1 seek={seek} conv=notrunc 2>/dev/null; else touch "{marker}"; fi;; esac\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; result = self.run_generator(root, "--output", str(output), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn(message, result.stderr)
            root, wrapper, output = self.fixture(str(Path(directory) / "output-race")), Path(directory) / "output-bin/cargo", Path(directory) / "output-race-out"; wrapper.parent.mkdir(); marker, trigger = Path(directory) / "output-marker", Path(directory) / "output-trigger"; wrapper.write_text(f'#!/bin/sh\nif [ -e "{trigger}" ] && [ ! -e "{marker}" ]; then printf "%s\\n" "{{\\\"invalid\\\":true}}" > "{output / DESCRIPTOR}"; touch "{marker}"; fi\nexec "{real}" "$@"\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; self.assertEqual(self.run_generator(root, "--output", str(output), env=env).returncode, 0); trigger.touch(); result = self.run_generator(root, "--check", str(output), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("output", result.stderr)
            root, target, output = self.fixture(str(Path(directory) / "output-link")), Path(directory) / "real-output", Path(directory) / "linked-output"; target.mkdir(); output.symlink_to(target, target_is_directory=True); sentinel = target / DESCRIPTOR; sentinel.write_text("unchanged\n"); result = self.run_generator(root, "--output", str(output)); self.assertNotEqual(result.returncode, 0); self.assertEqual(sentinel.read_text(), "unchanged\n"); self.assertFalse((target / LOCK).exists())
            root, wrapper, output = self.fixture(str(Path(directory) / "directory-race")), Path(directory) / "directory-bin/cargo", Path(directory) / "directory-output"; wrapper.parent.mkdir(); output.mkdir(); marker, moved = Path(directory) / "directory-marker", Path(directory) / "directory-moved"; wrapper.write_text(f'#!/bin/sh\nif [ "$1" = "--version" ] && [ -d "{output}" ] && [ ! -e "{marker}" ]; then mv "{output}" "{moved}"; mkdir "{output}"; touch "{marker}"; fi\nexec "{real}" "$@"\n'); wrapper.chmod(0o755); env["PATH"] = f'{wrapper.parent}:{os.environ["PATH"]}'; result = self.run_generator(root, "--output", str(output), env=env); self.assertNotEqual(result.returncode, 0); self.assertIn("output directory changed", result.stderr); self.assertFalse((output / DESCRIPTOR).exists() or (moved / DESCRIPTOR).exists())
    def test_structural_and_self_hash_drift_are_rejected(self):
        descriptor, lock = json.loads((SCHEMAS / DESCRIPTOR).read_bytes()), json.loads((SCHEMAS / LOCK).read_bytes()); paths = (("catalog", "schema_version"), ("catalog", "capacity", "max_entries"), ("support", "start_count", "max_horizons"), ("support", "funding_claim", "variants", 0), ("support", "outstanding_credit_vector", "max_dimensions"), ("support", "records", "ordinary_claims"), ("support", "records", "conditional_obligations"), ("support", "records", "pending_obligations"), ("cardinality_inputs", "ingress", "global_warming"), ("prepared_carry", "slots"), ("prepared_carry", "mandatory_suballocation_max"), ("prepared_carry", "safety_suballocation_max"), ("event_registry", "max_entries"), ("build_variants", "profiles", 0), ("native_inputs", "interface_revision"), ("section_identities", "executable_text", "cpu_type"), ("section_identities", "executable_text", "cpu_subtype"), ("section_identities", "executable_text", "sections", 0, "sha256"), ("section_identities", "native_text", "sha256"), ("toolchain", "python", "runtime_files", "sha256"), ("toolchain", "native_link", "sdk", "sha256"), ("toolchain", "native_link", "link_inputs", "sha256"), ("toolchain", "native_link", "linker_libraries", "sha256"))
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)
            for path in paths:
                candidate = json.loads(json.dumps(descriptor)); target = candidate
                for key in path[:-1]: target = target[key]
                value = target[path[-1]]; target[path[-1]] = value + 1 if isinstance(value, int) else value + "_drift"; blob = canonical(candidate); (output / DESCRIPTOR).write_bytes(blob); (output / LOCK).write_bytes(canonical({**lock, "digest": evidence(blob)})); self.assertNotEqual(self.run_generator(ROOT, "--check", str(output)).returncode, 0)
            descriptor["final_binary_sha256"] = "00" * 32; blob = canonical(descriptor); (output / DESCRIPTOR).write_bytes(blob); (output / LOCK).write_bytes(canonical({**lock, "digest": evidence(blob)})); result = self.run_generator(ROOT, "--check", str(output)); self.assertNotEqual(result.returncode, 0); self.assertIn("final binary self hash", result.stderr)
            foreign = self.fixture(str(Path(directory) / "foreign")); result = subprocess.run([sys.executable, "-I", "-S", "-B", "-c", BOOTSTRAP, str(ROOT / LAUNCHER), "--root", str(foreign), "--output", str(Path(directory) / "foreign-out")], cwd=ROOT, check=False, capture_output=True, text=True); self.assertNotEqual(result.returncode, 0); self.assertIn("executing generator", result.stderr); root = self.fixture(str(Path(directory) / "source-race")); path, replacement = root / "scripts/generate_daemon_core_build.py", root / ".work/replacement.py"; replacement.parent.mkdir(); source = path.read_text(); replacement.write_text(source.replace('"interface_revision":1', '"interface_revision":2', 1)); path.write_text(source.replace('if __name__ == "__main__": main()', f'if __name__ == "__main__": os.replace({str(replacement)!r}, __file__); main()')); self.rejects(root, Path(directory) / "source-race-out", "executing generator or launcher bytes"); root = self.fixture(str(Path(directory) / "launcher-race")); path, replacement = root / LAUNCHER, root / ".work/replacement-launcher.py"; replacement.parent.mkdir(); source = path.read_text(); replacement.write_text(source + "# replacement\n"); replacement.chmod(0o755); path.write_text(source.replace("import os, stat, sys; from pathlib import Path", f"import os, stat, sys; from pathlib import Path\nos.replace({str(replacement)!r}, __file__)")); self.rejects(root, Path(directory) / "launcher-race-out", "launcher bytes")
            result = subprocess.run([sys.executable, "-I", "-B", str(GENERATOR), "--root", str(ROOT), "--check", str(SCHEMAS)], cwd=ROOT, check=False, capture_output=True, text=True); self.assertNotEqual(result.returncode, 0); self.assertIn("-I -S -B", result.stderr); result = subprocess.run([sys.executable, "-I", "-S", "-B", str(GENERATOR), "--root", str(ROOT), "--check", str(SCHEMAS)], cwd=ROOT, check=False, capture_output=True, text=True); self.assertNotEqual(result.returncode, 0); self.assertIn("captured-source launcher", result.stderr)
if __name__ == "__main__": unittest.main()
